### ISSUE TITLE
Missing Synopses for Shots

### ISSUE THREAD

**Issue by BeiningWu** [showlab/Long-form-Video-Prior#2]
Thank you for your outstanding work on the Storyboard20K dataset and I have recently been working with your publicly available  Storyboard20K dataset.

However, it appears that for samples containing multiple shots, only the first shot has an associated synopsis.
For instance, a sample with four shots will only have the synopsis for the first shot, while the remaining five shots lack corresponding synopses.

![QQ截图20240623155440](https://github.com/showlab/Long-form-Video-Prior/assets/73815987/964b41e5-12ac-43ff-8bce-f283dfc7f840)

According to your dataset, I think the value of data[100]['synopses'] should be a list, where each element is a synopses list corresponding to a shot, and each synopses list contains 6 variants.

Could you please verify this issue and provide an update to the dataset with complete synopses for all shots in each sample? Your prompt attention to this matter would be highly appreciated.

**Comment by Sierkinhane** [comment]
hey!  sorry for the late reply. There are two kinds of synopses in our dataset, i.e., condensed (for movienet) and shot-by-shot (lsmdc). You can try `data[-1]['synopses']` you will see shot by shot synopses.

**Comment by BeiningWu** [comment]
Thanks for your reply. I have another question. Since i have downloaded all clips from lsmdc, so i try to reconstructed labeled image from the annotation. But i found the frame index in the clip doesn't match the suffix of the image file.
For example:
`data[9831]['key_frames'][0]='tt1071875/9831/3028_GHOST_RIDER_SPIRIT_OF_VENGEANCE_00.15.20.700-00.15.22.611_2.jpg'`
i use ffmpeg convert the video clip `3028_GHOST_RIDER_SPIRIT_OF_VENGEANCE_00.15.20.700-00.15.22.611.avi` to frame sequence and i select the thrid frame in the sequence. Then i found the label doesn't match the annotation.
![image](https://github.com/user-attachments/assets/b31ca77a-b93c-48a1-84fd-c1f2a218d75e)
Could you tell me what the index suffix of the image file mean or how didi you sample image frame from the clips?

**Comment by Sierkinhane** [comment]
Hi, we follow this repo https://github.com/hopeisme/Sc2St.

**Comment by BeiningWu** [comment]
Thanks for your reply!
